### ISSUE TITLE
根据域名进行代理的配置

### ISSUE THREAD

**Issue by rowthan** [eshengsky/noginx#3]
在配置项中有一个域名配置，但是目前看来这个部分似乎没有什么用。

想根据域名做代理 如 a.com 下的所有请求全部代理到 b 服务上，不知道这个功能目前是否支持？

**Comment by ddzyan** [comment]
同问，域名配置好像没什么用

**Comment by eshengsky** [comment]
如果外层还有其他代理服务器，比如nginx、阿帕奇，它们将请求转发到noginx后，noginx可能就会接收到不同域名的请求，此种情况下该配置有意义。
