### ISSUE TITLE
linux上运行报错

### ISSUE THREAD

**Issue by torns** [eshengsky/noginx#5]
linux上运行报错
![2](https://user-images.githubusercontent.com/23144884/54878349-53bc7080-4e66-11e9-87d3-aed4f7e2c589.png)

**Comment by rowthan** [comment]
> linux上运行报错
> ![2](https://user-images.githubusercontent.com/23144884/54878349-53bc7080-4e66-11e9-87d3-aed4f7e2c589.png)

修改一下配置文件 staticDirPath .linux系统没有分盘概念
